print("Welcome to the tip calculator!")
total = float(input("What was the total bill?: £"))
tip_percentage = float(input("What percentage tip would you like to give?: "))
tip_total = round(total * (tip_percentage / 100), 2)
new_total = round(total + tip_total, 2)
print(f"New total: £{new_total}. This includes a tip of: £{tip_total}")
number_of_people = float(input("How many people to split the bill?: "))
total_after_split = round(new_total / number_of_people, 2)
print(f"You need to pay £{total_after_split} each")